language: python
python:
  - "3.6"
  - "nightly"
install:
  - "pip install -r requirements.txt"
    # Don't forget testing requirements
  - "pip install -r requirements-test.txt"
# command to run tests
script: nosetests
